
const $=id=>document.getElementById(id);let session=null,catalog=null,draft=null,latest=null,busy=false,agentLocked=false,strategyTouched=false;
const statusNames={ready:'可继续',needs_clarification:'需要澄清',unfulfillable:'暂时无法满足'};
const issueNames={select_known_variant:'需要选择已登记的具体变体',missing_variant_evidence:'变体资料缺少核验依据',size_unspecified:'请明确尺码',substitution_requires_confirmation:'替代方案改变了明确要求，需要确认',unit_conversion_unverified:'包装数量尚未核实',quantity_unit_unspecified:'请明确数量是件数还是销售单位',cannot_split_catalog_pack:'所需件数不能完整换算为整包，请调整或选择其他包装',missing_rule_or_inventory:'缺少规则或库存资料',sales_region_not_allowed:'模拟销售规则不允许该地区',wholesale_minimum_not_met:'未达到模拟起订量',insufficient_stock:'当前模拟库存不足'};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function button(text,fn){const b=el('button',text,'secondary');b.type='button';b.onclick=()=>act(fn);return b}
async function api(path,body){const response=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(session?{'X-Session-ID':session}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data}
async function act(fn){if(busy||agentLocked)return;busy=true;$('message').textContent='处理中…';$('message').className='message';try{await fn();$('message').textContent=agentLocked?'Agent 运行中，完成后会更新结果。':'已完成，结果与依据已保存。'}catch(e){$('message').textContent=e.message;$('message').className='message error'}finally{busy=false}}
function localInput(date){return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function restoreOrderForm(){const r=draft.request,line=r.lines[0];for(const key of ['brand','size','color','quantity'])$(key).value=line[key]??'';$('unit').value=line.unit||'';$('style').value=line.style_id||'';$('region').value=r.sales_region;$('wholesale').checked=r.wholesale;$('ship').checked=r.needs_shipping;const chosen=draft.selections.find(s=>s.line_id===line.line_id);if(chosen)$('sku').value=chosen.sku;if(r.shipping){$('ready').value=localInput(new Date(r.shipping.ready_at));$('deadline').value=localInput(new Date(r.shipping.deadline_at));$('shipping-budget').value=r.shipping.budget_cents/100}$('ship').onchange()}
function order(){const line={line_id:'1',quantity:Number($('quantity').value),unit:$('unit').value||null,brand:$('brand').value,size:$('size').value,color:$('color').value.trim(),category:'t_shirt'};if($('style').value)line.style_id=$('style').value;const r={lines:[line],sales_region:$('region').value,wholesale:$('wholesale').checked,needs_shipping:$('ship').checked};if(r.needs_shipping)r.shipping={destination:'DE-DC',ready_at:new Date($('ready').value).toISOString(),deadline_at:new Date($('deadline').value).toISOString(),budget_cents:Math.round(Number($('shipping-budget').value)*100)};return r}
function details(title,data){const d=el('details');d.append(el('summary',title),el('pre',JSON.stringify(data,null,2)));return d}
async function reload(){draft=await api('/api/apparel/drafts/'+draft.id);localStorage.setItem('apparel-draft',draft.id);renderOrder();await renderProposals();updateOperationFields()}
function renderOrder(){const box=$('order-result');box.replaceChildren();const check=draft.confirmation?draft.proposals.find(p=>p.proposal_id===draft.confirmation.proposal_id).order_check:draft.order_check;box.append(el('span',draft.confirmation?'已确认本地模拟订单':statusNames[check.status],'badge '+(check.status==='ready'?'':'warn')));for(const item of check.lines){box.append(el('p',`${item.variant.brand} · ${item.variant.color} · ${item.variant.size} / ${item.catalog_units} 个销售单位 = ${item.pieces} 件`,'notice'))}for(const issue of check.issues)box.append(el('p',(issueNames[issue.code]||issue.code)+(issue.available_catalog_units!==undefined?`（库存 ${issue.available_catalog_units} 个销售单位，需要 ${issue.requested_catalog_units} 个）`:''),'notice error'));
for(const change of check.substitution_proposals){const approved=!check.issues.some(i=>i.approval_id===change.approval_id);box.append(el('p',change.differences.map(d=>`${d.field}: ${d.requested} → ${d.candidate}`).join('；'),'notice'));if(!approved)box.append(button('确认这一具体替代方案',async()=>{await api(`/api/apparel/drafts/${draft.id}/approve-substitution`,{approval_id:change.approval_id,expected_revision:draft.revision});await reload()}))}
if(!draft.confirmation)box.append(button('查看可供选择的替代候选',showAlternatives));box.append(details('查看逐项核验与资料依据',check));$('propose').disabled=check.status!=='ready'||!!draft.confirmation;$('download').disabled=false;$('run-agent').disabled=!!draft.confirmation;$('alternative-list').replaceChildren();}
async function showAlternatives(){const rows=await api(`/api/apparel/drafts/${draft.id}/alternatives/1`);const box=$('alternative-list');box.replaceChildren(el('h3','替代候选与差异'));if(!rows.length)box.append(el('p','当前资料和规则下没有可用候选。','notice'));for(const item of rows){const card=el('div',undefined,'item');card.append(el('p',item.title),el('p',item.differences.length?item.differences.map(d=>`${d.field}: ${d.requested} → ${d.candidate}`).join('；'):'满足当前明确的属性要求','notice'));card.append(el('p',`${item.quantity_conversion.catalog_units} 个销售单位 / ${item.quantity_conversion.pieces} 件；模拟可用库存 ${item.inventory.available_catalog_units}`,'notice'));card.append(button('选择并核验此候选',async()=>{await api(`/api/apparel/drafts/${draft.id}/select`,{selections:[{line_id:'1',sku:item.sku}],expected_revision:draft.revision});await reload()}));box.append(card)}}
async function renderProposals(){const box=$('proposal-list');box.replaceChildren();latest=draft.proposals.at(-1)||null;$('refresh').disabled=!latest;$('revise').disabled=!latest||!!draft.confirmation;$('cancel-flight').disabled=!latest||!!draft.confirmation||!latest.route.segments?.some(s=>s.mode==='air');if(!latest){box.append(el('p','订单满足条件后，可继续准备提案。','muted'));return}
for(const p of [...draft.proposals].reverse()){const card=el('div',undefined,'version'+(p.proposal_id!==latest.proposal_id?' old':''));card.append(el('h3',`版本 ${p.version} · ${p.state==='superseded'?'已被后续版本替代':p.state==='confirmed'?'已确认':p.state==='needs_adjustment'?'需要调整条件':'待核验与确认'}`));if(p.route.status==='planned'){const nums=el('div',undefined,'numbers');const money=el('div');money.append(el('strong',`$${(p.route.total_cost_cents/100).toFixed(2)}`),el('small','模拟运费 USD'));const arrival=el('div');arrival.append(el('strong',new Date(p.route.arrival_at).toLocaleDateString()),el('small','预计送达'));nums.append(money,arrival);card.append(nums);for(const s of p.route.segments){const segment=el('div',undefined,'route');segment.append(el('p',`${s.origin} → ${s.destination} · ${s.mode}`),el('p',`${new Date(s.departure_at).toLocaleString()} 出发 → ${new Date(s.arrival_at).toLocaleString()} 到达`,'notice'),el('p',`等待 ${(s.wait_minutes/60).toFixed(1)} 小时，含转运处理 ${(s.transfer_minutes/60).toFixed(1)} 小时`,'notice'));card.append(segment)}}else if(p.route.status==='not_required'){card.append(el('p','订单不需要运输，本提案仅核验商品与库存。','notice'))}else{card.append(el('p','原预算和交期内没有可行路线。以下调整必须由你选择，再创建更新后的订单要求。','notice error'));card.append(details('可选择的调整方向',p.route.adjustment_options||[]))}
if(p.proposal_id===latest.proposal_id&&!draft.confirmation){const validity=await api(`/api/apparel/drafts/${draft.id}/proposals/${p.proposal_id}/validity`);card.append(el('p',validity.valid?'当前版本核验有效。':'当前版本不能确认：'+validity.violations.join('、'),'notice '+(validity.valid?'':'error')));const confirm=button('单独确认此版本 · 生成模拟订单',async()=>{const result=await api(`/api/apparel/drafts/${draft.id}/proposals/${p.proposal_id}/confirm`,{});if(result.status==='rejected')throw Error('确认被拒绝：'+result.assessment.violations.join('、'));await reload()});confirm.disabled=!validity.valid;card.append(confirm)}card.append(details('提案原始依据与独立校验',p));box.append(card)}
if(draft.confirmation)box.prepend(el('p',`已生成 ${draft.confirmation.confirmation_id}；重复确认不会再次扣减模拟库存。`,'notice'))}
$('order-form').onsubmit=e=>{e.preventDefault();act(async()=>{draft=await api('/api/apparel/drafts',{order:order()});await api(`/api/apparel/drafts/${draft.id}/select`,{selections:[{line_id:'1',sku:$('sku').value}],expected_revision:draft.revision});await reload()})};
$('propose').onclick=$('revise').onclick=()=>act(async()=>{await api(`/api/apparel/drafts/${draft.id}/proposals`,{expected_revision:draft.revision});await reload()});$('refresh').onclick=()=>act(reload);
$('cancel-flight').onclick=()=>act(async()=>{const s=latest.route.segments.find(s=>s.mode==='air');const event={event_id:'UI-CANCEL-'+crypto.randomUUID(),kind:'cancel',leg_id:s.leg_id,nominal_departure:s.nominal_departure,published_at:new Date().toISOString()};await api('/api/apparel/events',event);$('event-status').textContent='已记录模拟取消事件：'+s.service_id+'。旧版资料保留，请查看有效性并修订。';await reload()});
$('download').onclick=()=>act(async()=>{const data=await api(`/api/apparel/drafts/${draft.id}/records`);const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=el('a');a.href=url;a.download=draft.id+'-records.json';a.click();URL.revokeObjectURL(url)});
$('ship').onchange=()=>{$('shipping-fields').hidden=!$('ship').checked;for(const id of ['ready','deadline','shipping-budget'])$(id).required=$('ship').checked};
async function init(){session=localStorage.getItem('apparel-session');if(session){try{await api('/api/apparel/catalog')}catch{session=null;localStorage.removeItem('apparel-session')}}if(!session){session=(await api('/api/sessions',{})).id;localStorage.setItem('apparel-session',session)}catalog=await api('/api/apparel/catalog');$('variant-count').textContent=catalog.variants.length;for(const v of catalog.variants){const option=el('option',`${v.brand} · ${v.color} · ${v.size} · ${v.sku}`);option.value=v.sku;$('sku').append(option)}$('inspect-sku').replaceChildren(...Array.from($('sku').options,o=>o.cloneNode(true)));$('sku').value='us:B06XWMKR2F';$('ready').value=localInput(new Date(Date.now()+86400000));$('deadline').value=localInput(new Date(Date.now()+7*86400000));const status=await api('/api/apparel/status');$('budget').textContent=`全项目预算上限 ¥${status.budget_limit_cny??0}；常规核验与路线计算不调用付费模型。`;const previous=localStorage.getItem('apparel-draft');if(previous){try{draft={id:previous};await reload();restoreOrderForm()}catch{localStorage.removeItem('apparel-draft');draft=null}}}


const operationNames={inspect_product:'查阅商品资料',check_order:'核验当前订单',stage_candidate:'选入替代供审阅',prepare_proposal:'准备提案',review_proposal:'复核当前提案'};
const operationPrompts={inspect_product:'查阅所选商品的指定资料字段，附来源依据，保持订单不变。',check_order:'只核验当前真实选择、库存、规则和已有批准，报告当前状态及具体问题依据。保持订单不变，等待我处理缺少的条件。',stage_candidate:'为所选明细行找到库存和规则合格、对明确要求改动最少的替代，实际选入供我审阅。列出差异并等我批准，不准备提案。',prepare_proposal:'保留当前已选商品及其具体批准，核验当前订单。条件明确且合格时按原预算与交期准备提案，附状态、费用和到达时间依据。不重新选品；缺少条件时说明问题，不确认订单。',review_proposal:'保留当前已选商品及其具体批准，读取事件并复核当前提案。有效则保留；失效则按原预算和交期修订，附旧版有效性和最终提案依据。不重新选品，不确认订单。'};
const taskDrafts={};let previousOperation='';
function updateOperationFields(){const mode=$('agent-operation').value;for(const id of ['inspect-sku-field','inspect-field-field'])$(id).hidden=mode!=='inspect_product';$('stage-line-field').hidden=mode!=='stage_candidate';const line=$('stage-line').value;$('stage-line').replaceChildren();for(const item of draft?.request.lines||[]){const o=el('option',`${item.line_id} · ${item.brand||''} · ${item.color||''} · ${item.size||'尺码待明确'}`);o.value=item.line_id;$('stage-line').append(o)}if(Array.from($('stage-line').options).some(o=>o.value===line))$('stage-line').value=line;
$('operation-hint').textContent=mode==='inspect_product'||mode==='check_order'?'本次只读资料与订单状态。':mode==='stage_candidate'?'选入候选供审阅，不表示已批准差异。':mode==='review_proposal'?(latest?'保留当前商品，复核版本 '+latest.version+'；确认仍由你单独操作。':'请先准备一份提案，再进行复核。'):mode==='prepare_proposal'?'保留当前商品与已批准差异，按原条件准备提案；更换商品请单独选入替代。':'自定义流程沿用已有执行方式；选择具体操作后，将核验最终状态与相应依据。';}
function operationPayload(){const mode=$('agent-operation').value;if(!mode)return null;const operation={mode};if(mode==='inspect_product'){operation.product_sku=$('inspect-sku').value;operation.product_fields=[$('inspect-field').value]}if(mode==='stage_candidate')operation.line_id=$('stage-line').value;if(mode==='review_proposal'){if(!latest)throw Error('请先准备提案，再复核当前版本。');operation.proposal_id=latest.proposal_id}return operation;}
$('agent-operation').onchange=()=>{taskDrafts[previousOperation]=$('agent-task').value;previousOperation=$('agent-operation').value;$('agent-task').value=taskDrafts[previousOperation]??operationPrompts[previousOperation]??taskDrafts['']??'';if(previousOperation==='inspect_product'&&draft?.selections[0])$('inspect-sku').value=draft.selections[0].sku;updateOperationFields()};
let currentJob=null;
function renderAgent(job){const box=$('agent-result');box.replaceChildren();box.append(el('p','本次结果的执行方式：'+({single:'单 Agent',coordinator:'协调员加专家',on_demand:'按需委派'}[job.arm]||job.arm),'notice'));if(job.operation)box.append(el('p','本次操作：'+operationNames[job.operation.mode],'notice'));if(job.notice)box.append(el('p',job.notice,'notice error'));if(job.status==='running'){box.append(el('p','Agent 正在读取资料和调用工具，请稍候。三种策略共用总调用上限；需要你确认的替代不会被自动批准。','notice'));return}const result=job.result;if(!result){box.append(el('p','本次运行 '+job.status+'；部分轨迹和费用记录已保留，没有自动重试。','notice error'));return}box.append(el('p',`模型调用 ${result.model_calls} 次 · 工具 ${result.tool_calls} 次 · ${result.latency_seconds.toFixed(1)} 秒 · 计入预算 ¥${Number(result.accounted_and_reserved_cny).toFixed(4)}`,'notice'));if(result.report){if(result.report.operation_check){box.append(el('p',result.report.operation_check.passed?'程序已核验本次操作的状态与必要依据。':'本次操作核验尚未通过。','notice'));const receipt=result.report.execution_receipt;if(receipt){box.append(el('p','实际选择：'+(receipt.selected_lines.map(s=>s.line_id+' → '+s.sku).join('；')||'尚未选入商品'),'notice'));if(receipt.current_proposal_id)box.append(el('p','当前提案：版本 '+receipt.current_proposal_version+' · '+receipt.current_proposal_id,'notice'));}}box.append(el('span',statusNames[result.report.decision.status]||'资料查询','badge'));if(result.report.decision.product_skus.length)box.append(el('p','候选：'+result.report.decision.product_skus.join('、'),'notice'));if(result.report.decision.question_codes.length)box.append(el('p',result.report.decision.question_codes.map(c=>issueNames[c]||c).join('；'),'notice'));box.append(details('查看有依据的字段、决定与委派理由',result.report))}else{box.append(el('p','尚未形成完整结果：'+result.run_status+'。本次运行保留在失败分母中。','notice error'))}box.append(button('下载本次 Agent 完整轨迹',async()=>{downloadJSON(await api('/api/apparel/runs/'+job.job_id+'/records'),job.job_id+'-records.json')}))}
function downloadJSON(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000)}
async function pollAgent(){try{const job=await api('/api/apparel/runs/'+currentJob);renderAgent(job);if(job.status==='running'){setTimeout(pollAgent,1800);return}agentLocked=false;await reload();$('message').textContent='Agent 运行已结束，程序核验和版本记录已更新。';localStorage.removeItem('apparel-active-job')}catch(e){agentLocked=false;$('message').textContent='读取 Agent 状态失败：'+e.message+'；刷新页面后可以恢复查看。'}}
$('run-agent').onclick=()=>act(async()=>{const job=await api('/api/apparel/drafts/'+draft.id+'/agent',{task:$('agent-task').value,arm:$('agent-arm').value,operation:operationPayload()});currentJob=job.job_id;localStorage.setItem('apparel-active-job',currentJob);agentLocked=true;$('run-agent').disabled=true;renderAgent(job);setTimeout(pollAgent,1000)});
act(async()=>{await init();await loadStudy();if(draft){const previous=await api('/api/apparel/drafts/'+draft.id+'/agent/latest');if(previous){currentJob=previous.job_id;renderAgent(previous);if(previous.status==='running'){agentLocked=true;$('run-agent').disabled=true;setTimeout(pollAgent,500)}}}});

async function loadStudy(){const study=await api('/api/apparel/research');const names={single:'单 Agent',coordinator:'协调员加专家',on_demand:'按需委派'};const box=$('study-table');box.replaceChildren();if(study.status!=='complete'){$('study-status').textContent=(study.status==='test_running'?'独立测试运行中':study.status==='validation_running'?'验证运行中':'开发阶段')+`：已保存 ${study.runs_completed}/${study.runs_planned} 次任务。未完成前不公布最终优胜结论。`;return}
$('study-status').textContent=`${study.cases_per_arm} 个预设模拟任务 × 3 种策略，${study.runs_completed} 次运行与逐例证据完整。`;const table=el('table');table.append(el('caption','补充任务完成率和原始严格清单同时展示；费用包含未确认调用的预留。'));const head=el('tr');for(const label of ['策略','任务完成（补充）','原严格清单','平均费用 CNY','平均时延','P95 时延','约束违规']){const th=el('th',label);th.scope='col';head.append(th)}const thead=el('thead');thead.append(head);table.append(thead);const body=el('tbody');for(const arm of ['single','coordinator','on_demand']){const s=study.arms[arm],old=study.strict_v1_arms[arm];const row=el('tr');for(const value of [names[arm],`${s.task_completed}/${s.scheduled} (${(s.task_accuracy*100).toFixed(1)}%)`,`${old.task_completed}/${old.scheduled}`,Number(s.avg_cost_cny).toFixed(4),s.avg_latency_seconds.toFixed(1)+' s',s.p95_latency_seconds.toFixed(1)+' s',String(s.constraint_violation_runs)])row.append(el('td',value));body.append(row)}table.append(body);box.append(table);$('study-note').textContent=study.metric_notice+' 默认策略按验证集预先选择：'+(study.default_enabled?names[study.selected_arm]:'暂不自动推荐')+'。补充口径在最终测试前登记，原始分数与后续类型检查修复记录均保留。';if(study.default_enabled&&!strategyTouched)$('agent-arm').value=study.selected_arm;$('study-note').textContent+=' 按需委派组实际调用专家 '+study.arms.on_demand.delegation_runs+'/'+study.cases_per_arm+' 个任务；本轮未证明按需协作收益。';box.append(details('查看按任务类型的结果与配对区间',{families:study.families,paired_differences:study.paired_differences}))}
$('refresh-study').onclick=()=>act(loadStudy);
$('agent-arm').onchange=()=>{strategyTouched=true};
